import { useEffect, useState } from 'react'; import { motion } from 'framer-motion'; import { Link } from 'react-router-dom';
import { ArrowDown, Braces, Check, Cloud, Code2, Database, Github, HeartPulse, Layers3, Linkedin, Mail, MapPin, MessageCircle, Smartphone, Sparkles, Zap } from 'lucide-react';
import Navbar from '../components/Navbar'; import Footer from '../components/Footer'; import Background from '../components/Background'; import ProjectVisual from '../components/ProjectVisual'; import { Counter, MagneticLink, Reveal, SectionHeading } from '../components/UI'; import { projects } from '../data';
import MobileExpertise from '../components/MobileExpertise';
import { publicAsset } from '../config';

const skillGroups={Frontend:['React Native','Expo','React Navigation','Redux','Axios','AsyncStorage','Secure Storage','Google Maps SDK','Image Picker','Camera Integration','React','TypeScript'],Backend:['Node.js','Express','.NET','Entity Framework','Python','Django'],Databases:['MongoDB','Firebase','Supabase','SQL Server','PostgreSQL'],Tools:['Git','GitHub','VS Code','Postman','Figma','Docker']};
const api=[{name:'Node.js / Express',copy:'Scalable services for product teams that value speed without sacrificing structure.',items:['JWT authentication','Role-based authorization','CRUD APIs','File upload & image processing','Email & payment services','Logging & validation','Swagger docs']},{name:'.NET',copy:'Robust enterprise APIs designed around maintainability, security, and clean data access.',items:['Entity Framework','LINQ','Repository pattern','Dependency injection','Authentication','SQL Server','Stored procedures']},{name:'Django',copy:'Productive Python backends with batteries-included administration and dependable APIs.',items:['Django REST Framework','Authentication','CRUD APIs','Django admin panel','ORM']}];
const realtime=[['Firebase Firestore','Live patient charts and synchronized messaging data.'],['Firebase Auth','Secure identity flows across healthcare and chat apps.'],['Supabase Realtime','Low-latency subscriptions for MaxChats conversations.'],['Push notifications','Timely reminders and new-message alerts on mobile.'],['Cloud functions','Event-driven automation outside the client lifecycle.'],['Socket.io','Bidirectional events for scheduling and dashboards.'],['Live synchronization','Consistent state across customers, teams, and operators.'],['Offline support','Resilient mobile workflows with eventual synchronization.'],['Real-time dashboards','Fresh operational signals without manual refreshes.']];

function Loading(){const [show,setShow]=useState(true);useEffect(()=>{const seen=sessionStorage.getItem('intro');const t=setTimeout(()=>{setShow(false);sessionStorage.setItem('intro','1')},seen?0:850);return()=>clearTimeout(t)},[]);return show?<motion.div className="loader" exit={{opacity:0}}><motion.div animate={{rotate:360}} transition={{repeat:Infinity,duration:1,ease:'linear'}}>Hamza Mustafa<span>.</span></motion.div></motion.div>:null}
function TypedHeadline(){const full='Hamza Mustafa';const [text,setText]=useState(full);useEffect(()=>{let i=0;setText('');const id=setInterval(()=>{i++;setText(full.slice(0,i));if(i===full.length)clearInterval(id)},75);return()=>clearInterval(id)},[]);return <>{text}<i className="caret"/></>}
export default function Home(){const [tab,setTab]=useState(0);return <><Loading/><Navbar/><Background/><main id="top">
 <section className="hero"><div className="blob blob-a"/><div className="blob blob-b"/><div className="hero-copy"><motion.div className="availability" initial={{opacity:0,y:10}} animate={{opacity:1,y:0}}><i/> Available for meaningful work</motion.div><motion.p className="kicker" initial={{opacity:0}} animate={{opacity:1}} transition={{delay:.15}}>HELLO, I'M HAMZA MUSTAFA</motion.p><motion.h1 initial={{opacity:0,y:24}} animate={{opacity:1,y:0}} transition={{delay:.25}}><TypedHeadline/><br/><span>Senior React Native Developer <em>·</em> Full-Stack Engineer</span></motion.h1><motion.p className="hero-bio" initial={{opacity:0,y:18}} animate={{opacity:1,y:0}} transition={{delay:.42}}>I build scalable iOS and Android applications with React Native, Expo, TypeScript, real-time services, secure APIs, and the full-stack expertise required to take products to production.</motion.p><motion.div className="hero-actions" initial={{opacity:0,y:18}} animate={{opacity:1,y:0}} transition={{delay:.55}}><MagneticLink href="#projects">View projects</MagneticLink><MagneticLink href={publicAsset('resume.pdf')} secondary download>Download résumé</MagneticLink><a className="text-link" href="#contact">Contact me <ArrowDown size={16}/></a></motion.div></div><div className="hero-orbit"><div className="orbit-ring one" aria-hidden="true"/><div className="orbit-ring two" aria-hidden="true"/><motion.div className="core profile-core" animate={{y:[0,-10,0]}} transition={{repeat:Infinity,duration:4}}><img src={publicAsset('images/hamza-profile.webp')} width="460" height="460" alt="Hamza Mustafa, senior React Native developer"/></motion.div>{[[Braces,'a'],[Database,'b'],[Smartphone,'c'],[Cloud,'d']].map(([Icon,pos]:any)=><motion.div key={pos} aria-hidden="true" className={`float-icon ${pos}`} animate={{y:[0,-7,0]}} transition={{repeat:Infinity,duration:3+Number(pos.charCodeAt(0)%2),delay:Number(pos.charCodeAt(0)%3)/3}}><Icon/></motion.div>)}</div><a className="scroll-cue" href="#about"><span/> Scroll to explore</a></section>

 <section id="about" className="section about"><SectionHeading eyebrow="About Hamza Mustafa" title="React Native expertise. Full-stack ownership."/><div className="about-grid"><Reveal direction="left"><img className="about-portrait" src={publicAsset('images/hamza-profile.webp')} width="460" height="460" loading="lazy" alt="Portrait of Hamza Mustafa, React Native and full-stack developer"/><p className="lead">I specialize in production React Native applications and own the complete journey—from polished mobile UX to APIs, databases, real-time services, and store releases.</p></Reveal><Reveal delay={.1}><p>React Native is my primary craft, supported by experience with Expo managed and bare workflows, JavaScript, TypeScript, Redux, Firebase, SignalR, REST and GraphQL APIs, Node.js, Express, MongoDB, and SQLite. I build native-feeling iOS and Android experiences without losing sight of maintainable architecture.</p><p>As a team lead and senior developer, I collaborate through Git/GitHub, debugging, performance optimization, native module integration, and pragmatic architecture—staying close to users and business outcomes from discovery through production.</p><div className="about-points"><span><Check/> React Native specialist</span><span><Check/> Full-stack ownership</span><span><Check/> Production app delivery</span></div></Reveal></div></section><MobileExpertise/>

 <section id="projects" className="section"><SectionHeading eyebrow="Selected work" title="Products shaped around real problems." copy="A selection of healthcare, enterprise, communication, and consumer platforms. Each case study shows the thinking behind the interface."/><div className="projects-grid">{projects.map((p,i)=><Reveal key={p.slug} delay={(i%2)*.08}><Link className="project-card" to={`/projects/${p.slug}`}><ProjectVisual title={p.title} accent={p.accent} compact/><div className="project-card-copy"><div><span>{p.eyebrow}</span><h3>{p.title}</h3><p>{p.description}</p></div><i><ArrowDown/></i></div><div className="badges">{p.tech.map(t=><span key={t}>{t}</span>)}</div></Link></Reveal>)}</div></section>

 <section className="section contributions"><SectionHeading eyebrow="Other contributions" title="The systems behind great products."/><div className="contribution-grid">{['SaaS product development','Enterprise applications','Admin dashboards','Healthcare systems','Business platforms','REST API development','Authentication systems','Cloud integrations','Payment integrations','Notification systems'].map((x,i)=><Reveal key={x} delay={(i%5)*.04}><div className="contribution"><span>{String(i+1).padStart(2,'0')}</span><p>{x}</p></div></Reveal>)}</div></section>

 <section id="expertise" className="section"><SectionHeading eyebrow="Backend & API expertise" title="Strong foundations beyond the interface."/><div className="api-tabs" role="tablist">{api.map((a,i)=><button className={i===tab?'active':''} onClick={()=>setTab(i)} role="tab" aria-selected={i===tab} key={a.name}>{a.name}</button>)}</div><motion.div className="api-panel" key={tab} initial={{opacity:0,y:10}} animate={{opacity:1,y:0}}><div><span className="eyebrow">0{tab+1} / API SYSTEMS</span><h3>{api[tab].name}</h3><p>{api[tab].copy}</p></div><div className="feature-list">{api[tab].items.map(x=><span key={x}><Check/>{x}</span>)}</div></motion.div></section>

 <section className="section realtime"><SectionHeading eyebrow="Real-time technology" title="Experiences that stay current." copy="Reliable live data is a product feature—not just an infrastructure choice. These tools keep teams informed, mobile workflows resilient, and customer interactions immediate."/><div className="realtime-grid">{realtime.map(([name,copy],i)=><Reveal key={name} delay={(i%3)*.05}><div className="realtime-card"><Zap/><h3>{name}</h3><p>{copy}</p></div></Reveal>)}</div></section>

 <section className="section"><SectionHeading eyebrow="Data layer" title="The right database for the job."/><div className="database-row">{[['MongoDB','Flexible document models for fast-evolving products.'],['Firebase','Real-time mobile data and offline-first flows.'],['Supabase','Postgres foundations with modern realtime services.'],['SQL Server','Structured enterprise data and stored procedures.'],['PostgreSQL','Relational integrity for scalable applications.']].map(([n,c])=><div className="database-card" key={n}><Database/><h3>{n}</h3><p>{c}</p></div>)}</div></section>

 <section className="section stack"><SectionHeading eyebrow="Technology stack" title="Tools I use to ship."/><div className="stack-grid">{Object.entries(skillGroups).map(([group,items],i)=><Reveal key={group} delay={i*.06}><div className="stack-group"><div className="stack-icon">{[Layers3,Code2,Database,Sparkles].map((I,j)=>j===i?<I key={j}/>:null)}</div><h3>{group}</h3><div>{items.map(x=><span key={x}>{x}</span>)}</div></div></Reveal>)}</div></section>

 <section id="experience" className="section"><SectionHeading eyebrow="Experience" title="A career built through ownership."/><div className="timeline">{[['Senior React Native & Full Stack Engineer','Present','Leading production mobile delivery across iOS, Android, APIs, real-time systems, and product architecture.'],['React Native Developer','Specialization','Built healthcare, marketplace, messaging, and business applications with complex native-feeling workflows.'],['Full Stack Developer','Foundation','Created dependable web platforms and backend services using JavaScript, .NET, Python, and cloud databases.']].map((x,i)=><Reveal key={x[0]}><div className="timeline-item"><i/><span>{x[1]}</span><div><h3>{x[0]}</h3><p>{x[2]}</p></div></div></Reveal>)}</div></section>

 <section className="section services"><SectionHeading eyebrow="Services" title="From product idea to production system."/><div className="service-grid">{[[Code2,'Full-stack development','Thoughtful interfaces and resilient backend systems delivered as one cohesive product.'],[Smartphone,'Mobile app development','Cross-platform React Native apps with native-quality interaction and robust offline behavior.'],[Cloud,'API & cloud architecture','Secure REST APIs, real-time services, integrations, and deployment workflows.'],[HeartPulse,'Healthcare platforms','Clear, role-aware tools designed around demanding operational and clinical workflows.']].map(([Icon,n,c]:any)=><Reveal key={n}><div className="service-card"><Icon/><h3>{n}</h3><p>{c}</p></div></Reveal>)}</div></section>

 <section className="stats"><div className="stat"><Counter value={20}/><span>Projects delivered</span></div><div className="stat"><Counter value={5}/><span>Enterprise applications</span></div><div className="stat"><Counter value={10}/><span>REST APIs</span></div><div className="stat"><Counter value={5}/><span>Healthcare systems</span></div><div className="stat"><Counter value={100} suffix="%"/><span>Client satisfaction</span></div></section>

 <section className="section testimonials"><SectionHeading eyebrow="Kind words" title="Trusted collaboration, measured by outcomes."/><div className="testimonial-grid">{['“A thoughtful engineering partner who sees both the system and the user experience.”','“Consistently turns complex workflows into software that feels focused and dependable.”','“Strong ownership, clear communication, and a rare attention to product detail.”'].map((q,i)=><Reveal key={q} delay={i*.07}><blockquote>{q}<footer><div className="avatar">{String.fromCharCode(65+i)}</div><div><strong>Client testimonial</strong><span>Verified reference placeholder</span></div></footer></blockquote></Reveal>)}</div></section>

 <section id="contact" className="section contact"><div className="contact-copy"><span className="eyebrow">Let's work together</span><h2>Have a mobile product to build?</h2><p>I’m open to React Native roles, mobile product leadership, and full-stack projects where thoughtful engineering makes a measurable difference.</p><div className="contact-links"><a href="https://github.com/hamza229hafeez" target="_blank" rel="noreferrer"><Github/>GitHub</a><a href="https://www.linkedin.com/in/hamza-hafeez-5567a9200" target="_blank" rel="noreferrer"><Linkedin/>LinkedIn</a><a href="mailto:hafeezhamza628@gmail.com"><Mail/>hafeezhamza628@gmail.com</a><a href="https://wa.me/923175487766" target="_blank" rel="noreferrer"><MessageCircle/>WhatsApp</a><span><MapPin/>Rawalpindi, Pakistan · Open to remote</span></div><MagneticLink href={publicAsset('resume.pdf')} secondary download>Download résumé</MagneticLink></div><form action="https://formsubmit.co/hafeezhamza628@gmail.com" method="POST"><label>Name<input name="name" required autoComplete="name" placeholder="Your name"/></label><label>Email<input type="email" name="email" required autoComplete="email" placeholder="you@company.com"/></label><label>What are you building?<textarea name="message" required rows={5} placeholder="Tell me about the role, product, or challenge…"/></label><input type="hidden" name="_subject" value="Portfolio inquiry for Hamza Mustafa"/><input type="hidden" name="_captcha" value="false"/><button className="button" type="submit">Send message <ArrowDown/></button><small>Delivered securely to Hamza Mustafa by FormSubmit. No data is stored on this site.</small></form></section>
 </main><Footer/></>}
