import { Award, Gauge, GitBranch, Layers3, ShieldCheck, Smartphone } from 'lucide-react';
import { Reveal, SectionHeading } from './UI';
import { publicAsset } from '../config';
const responsibilities=[
 {icon:Smartphone,title:'Production mobile delivery',copy:'Build and release scalable React Native applications for iOS and Android using Expo managed and bare workflows.'},
 {icon:Layers3,title:'Architecture & integration',copy:'Design clean feature architecture and integrate REST, GraphQL, Firebase, SignalR, and native modules.'},
 {icon:Gauge,title:'Performance & quality',copy:'Debug complex mobile issues, reduce unnecessary rendering, and keep animations and high-density screens responsive.'},
 {icon:ShieldCheck,title:'Secure mobile experiences',copy:'Implement authentication, secure storage, permission-aware device features, and dependable real-time data flows.'},
 {icon:GitBranch,title:'Technical leadership',copy:'Lead delivery, review code, coordinate releases, and translate product requirements into achievable engineering work.'},
 {icon:Award,title:'Pixel-perfect UI',copy:'Create accessible, intuitive interfaces with precise spacing, responsive layouts, and native-feeling interactions.'}
];
const mobileStack=['React Native','Expo','TypeScript','React Navigation','Redux','Axios','AsyncStorage','Secure Storage','Firebase','SignalR','Google Maps SDK','Image Picker','Camera Integration','REST & GraphQL APIs'];
export default function MobileExpertise(){return <section id="mobile-experience" className="section mobile-expertise"><SectionHeading eyebrow="React Native experience" title="Mobile is my primary engineering craft." copy="I lead and deliver production applications across healthcare, marketplaces, messaging, and business operations—with full-stack context and an uncompromising focus on mobile quality."/><div className="mobile-profile"><Reveal direction="left" className="profile-photo-card"><img src={publicAsset('images/hamza-profile.webp')} width="460" height="460" loading="lazy" alt="Hamza Mustafa, React Native developer"/><div><span>Based in Rawalpindi, Pakistan</span><strong>Team Lead & Senior React Native Developer</strong><p>React Native · Expo · iOS · Android</p></div></Reveal><Reveal className="mobile-stack-card"><span className="eyebrow">Mobile toolkit</span><div className="mobile-stack">{mobileStack.map(item=><span key={item}>{item}</span>)}</div></Reveal></div><div className="responsibility-heading"><span className="eyebrow">Responsibilities & achievements</span><h3>Ownership beyond feature delivery.</h3></div><div className="responsibility-grid">{responsibilities.map(({icon:Icon,title,copy},index)=><Reveal key={title} delay={(index%3)*.05}><article><Icon/><h3>{title}</h3><p>{copy}</p></article></Reveal>)}</div></section>}
